### ISSUE TITLE
locals[0] does not appear to be a `module` object with Hot Module replacement API enabled.

### ISSUE THREAD

**Issue by golden-hu** [vikingmute/webpack-react-codes#10]
在学到第4章的最后的时候，
前面的测试都可以了
在敲完"test Deskmark create one post and delete a post这段代码之后，就出现这个问题：
Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr
结合github
我将.babelrc .eslinerc webpack.config.js都与github中代码一致了。还是存在这个问题
请赐教

**Comment by vikingmute** [comment]
@golden-hu  在package.json 里面的 test 命令 应该是这样的： "test": "NODE_ENV=production mocha --compilers js:babel-core/register --require ignore-styles 注意这里会把NODE_ENV=production，这ENV 会禁用react-ransform-hmr 这个插件， 要不就会有这个错误。文章里面应该对这个做过介绍：

你修改以后试试。

**Comment by nighca** [comment]
想起来在 windows 环境下不能通过直接 `NODE_ENV=xxx` 来设置环境变量，就像 https://github.com/vikingmute/webpack-react-codes/issues/11 这里说的。

@golden-hu 如果你是 windows 环境，可以尝试下上边 issue https://github.com/vikingmute/webpack-react-codes/issues/11 里的做法，不行的话参考这里：http://stackoverflow.com/questions/9249830/how-can-i-set-node-env-production-in-windows
