### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by venoral** [vikingmute/webpack-react-codes#11]
109页在package.json中添加test命令，建议标注一下windows环境为
`"test": "set NODE_ENV=production && mocha --compilers js:babel-core/register --require ignore-styles"`，以免会误导初学者~感谢！

**Comment by vikingmute** [comment]
@venoral 好的 谢谢你的建议欧 我回去看一下 然后会加到勘误表里面

**Comment by vikingmute** [comment]
@venoral @nighca 已经添加到勘误表中 非常感谢你的建议 
https://github.com/vikingmute/webpack-react-codes/commit/7952bf3238cd704a3827e6d57cf2a6d5c505818c
