### ISSUE TITLE
关于书中三处疑问

### ISSUE THREAD

**Issue by BrainYang** [vikingmute/webpack-react-codes#12]
1、	p74，如果不用源码，按照书上步骤，好像得不到书上截图效果。'containter' 是哪来的？

2、	p84，最好注明一下，在`Profile.jsx`的`constructor`函数中，需要加上
	`this.addHobbyCallback = this.addHobbyCallback.bind(this);`
    不然，在`Chrome`的控制台中会出现错误，指向`addHobbyCallback`函数 :
    `Uncaught TypeError: Cannot read property 'refs' of null.`
    这个错误提示让人迷惑，看上去refs有关系，跟函数没有关系。

3、	chapter4\part1 的 app.jsx 文件中有这么一行：
	`import 'bootstrap/scss/bootstrap.scss;`
    我下载的[bootstrap v4.0.0-alpha.5](http://getbootstrap.com/2.3.2/assets/bootstrap.zip)中并没有这样的文件。
    随书源码用的是`bootstrap v4.0.0-alpha.2`(见`package.json`，`"bootstrap": "^4.0.0-alpha.2"`)，不知是不是bootstrap版本问题？

**Comment by nighca** [comment]
@BrainYang 我去 check 了下，v4.0.0-alpha.5 中也是应该有这个文件的：https://github.com/twbs/bootstrap/blob/v4.0.0-alpha.5/scss/bootstrap.scss

看起来你是手动下载的 bootstrap 的结果文件？建议使用 npm 进行依赖的安装然后再试下。

**Comment by nighca** [comment]
1、2 的话可能是书里没有提到，抱歉疏忽，我回去再检查下。代码的话以这个仓库里的为准哈，书里的介绍毕竟只是节选了部分关键代码进行说明。

**Comment by vikingmute** [comment]
@BrainYang 你好 你说的问题好多读者也有相同的反馈 其中因为这点很多人也是颇有微词 我和 @nighca 最开始写本书的目的就是不想复制大段的代码在书里面 主要是讲关键步骤和主要的代码 其它省略掉 让读者自行到这个repo中阅读，不知道你更喜欢哪种方式？我们是否应该把所有代码都完善到书里？

**Comment by BrainYang** [comment]
@nighca 确实是手动从官网下载的。还真和`npm`安装的不一样。
即使是用npm安装，`-gd` 和 `--save-dev`最后得到的文件也不一样。

@vikingmute 这本书能让选定React框架做开发的人员对相关技术有个全面大概的了解。
我刚接触React，喜欢按照书上讲的步骤，边做边看效果。
如果用React开发熟练了，也许看书就行了，根本不用上机试。
如果只是翻翻书，然后把源码跑一遍验证一下，那会少思考很多问题。
对于新手来说，必须要动手做才行，跑源码都不一定能成功。
在动手做的过程中，关键点书上没讲，自己也没想到看源码、或者源码看不懂，
结果运行不了，或出错，或与书上结果不一样，网上又搜不到答案，
就会有一种挫败感，兴趣也就跟着降低。

**Comment by nighca** [comment]
@BrainYang 估计是不同方式安装的版本不一样导致的，可以直接安装本仓库对应的源码中（`package.json`）指定的版本哈，应该可以避免结果不同的问题。
