### ISSUE TITLE
一点问题请教

### ISSUE THREAD

**Issue by venoral** [vikingmute/webpack-react-codes#13]
在码P135页代码时候，引入“handlebars”模块，npm警告报错如下：
`WARNING in ./~handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.`
`ERROR in ./~/handlebars/lib/index.js
Module not found: Error: Cannot resolve module 'fs' in f:\..\node_modules\handlebars\lib
@ ./~/handlebars/lib/index.js 17:10-23`
看起来提示是让安装一个loader解决，但是并没.hbs文件呐~
报错说找不到fs模块，这是为什么明明是在node中运行的啊... 
通过进入/handlebars/lib/index.js文件删除掉`require('fs')`语句或在webpack.config.js中配置`node: { fs: "empty"}`能解决掉报错，但是警告依然存在。
求解答~~

**Comment by nighca** [comment]
@venoral 你好，这里引入的 handlebars 是直接在浏览器中，而不是在构建时（Node.js 环境中）执行的，这里 webpack 的 WARNING 看起来是 handlebars 包为了让 Node.js 的 `require` 可以用来加载 handlebars 模板资源做的工作导致的，不影响 handlebars 包本身在浏览器中的使用。

handlebars 包的代码里也注释说明了：
```javascript
// Publish a Node.js require() handler for .handlebars and .hbs files
```

**Comment by venoral** [comment]
好的，了解！
