### ISSUE TITLE
有没有人是因为书上例子无法运行成功放弃这本书了！

### ISSUE THREAD

**Issue by lmdiloveu** [vikingmute/webpack-react-codes#14]
这里最新的代码也很多有问题，既然是学习，有几个人能指出错误的地方！

**Comment by vikingmute** [comment]
@lmdiloveu 哪个例子没有运行起来？

**Comment by nighca** [comment]
@lmdiloveu 谢谢提出意见，书上的代码确实不是完整的，因为我们觉得把所有的代码都贴到文字里打印出来价值不大，而且会影响阅读体验。我们的做法是节选有代表性的部分进行说明，而完整的代码以代码仓库的方式提供出来。
这个仓库里的代码都是经过验证可以较方便地运行的，但是我们确实做不到把所有系统各种环境都测试一遍。所以我们通过说明环境信息（Node.js、React 等版本）以及类似 npm shrinkwrap 等手段，希望尽可能保证读者能达到跟我们一致的运行效果。
如果有运行失败的情况，麻烦提供下详细的信息（包括环境及错误内容等），我们可以协助分析，如有普遍的问题我们会通过代码配置或文档的手段以避免类似的问题。
