### ISSUE TITLE
第四章的笔记本项目例子，需要node-sass包

### ISSUE THREAD

**Issue by lmdiloveu** [vikingmute/webpack-react-codes#15]
安装npm install node-sass --save-dev的时候，电脑还需要有Python环境！这书都没说，找半天问题

**Comment by nighca** [comment]
@lmdiloveu 你好，node-sass 依赖二进制包，正常情况下会优先下载预编译好的二进制包，不需要安装时编译（安装时编译才会依赖 Python）。预编译的版本支持的环境可以参考这里：https://github.com/sass/node-sass/releases/tag/v3.4.2

所以如果需要现编译的话，可能是：
1. 你的系统或环境不在预编译支持的列表里
2. 下载二进制包失败（墙的原因导致从命令行访问 github.com 失败）

方便的话把 npm 报告的错误信息发在这看下

**Comment by lmdiloveu** [comment]
@nighca 谢谢回复，应该就是你说的问题，自己手动下载搞定吧
