### ISSUE TITLE
第四张例子

### ISSUE THREAD

**Issue by uimake** [vikingmute/webpack-react-codes#16]
我是直接用你们的源码
1.其中deskmark里的saveItem方法里有错误提示
`./component/DeskMark/index.jsx`
> Module build failed: SyntaxError: Unexpected token, expected , (61:12)

```
  59 |           exist.id === item.id
  60 |           ? {
> 61 |             ...exist,
     |             ^
  62 |             ...item,
  63 |           }
  64 |           : exist
```

2.还有itemEditor里，是同一类错误，还有这里为什么在用save包装一次（为了this?）,还有item在deskmark里面怎么传到这里？
```
let save = () => {
      onSave({
        ...item,
        title: this.refs.title.value,
        content: this.refs.content.value,
      });
    };
```

**Comment by nighca** [comment]
@uimake 谢谢反馈，帮你整理了下代码的格式。

1. 这里 `{ ...exist }` 是目前 [stage3 的提案](https://github.com/sebmarkbage/ecmascript-rest-spread)引入的语法，我们在 [`.babelrc`](https://github.com/vikingmute/webpack-react-codes/blob/master/chapter4/part1/.babelrc) 通过 `transform-object-rest-spread` 这个 plugin 做了支持。你这里报了语法错误，是不是有手动修改配置，或者依赖没有正确安装？

2. 这里将方法定义为变量 `save`，而不是在使用的地方直接使用匿名函数，是为了避免在后面的 jsx 中写太多的 Javascript 逻辑，提高界面内容部分的可读性。`item` 是从 component 的 `props` 上获得的（父组件通过 `props` 的方式传入），见[这里](https://github.com/vikingmute/webpack-react-codes/blob/master/chapter4/part1/app/components/ItemEditor/index.jsx#L21)以及[这里](https://github.com/vikingmute/webpack-react-codes/blob/master/chapter4/part1/app/components/Deskmark/index.jsx#L112)。

**Comment by uimake** [comment]
回复的很及时，👍一个，是transform-object-rest-spread没有配置，我这里是渐进式配置，不是一次行把所有都配置好，由于node npm webpack等都是最新版本，没有按书中的指定版本，所以配置不是一模一样的。
