### ISSUE TITLE
第六章例子

### ISSUE THREAD

**Issue by uimake** [vikingmute/webpack-react-codes#17]
147页 connect连接store与组件 Counter(props){ onClick={props.onBtnClick}}
这个onBtnClick（props属性）不是应该由父组件传入的吗，这里直接用自己的为什么不写onClick={this.onBtnClick}

还有实例代码
```javascript
// create root component based on component Deskmark
const App = connect(
  state => ({ state }),
  dispatch => ({
    actions: bindActionCreators(actionCreators, dispatch),
  })
)(Deskmark);
```
这样做是不是所有子组件的props里都有{state,actions}, 这里的state是把所有的reducer里面的初始化state都合并了？actions是把actionCreators添加dispatch后的一个手柄？

另外这个state和actions能换名字吗，还是固定字段？

请问下面这个函数的执行完以后返回值是什么，
比如
```javascript
var returnVal = fetchEntryList(); console.log(returnVal);
function fetchEntryList() {
  return dispatch => {
    storage.getAll()
      .then(items => dispatch(updateEntryList(items)));
  };
}
```

我看updateEntryList最终执行函数是
```javascript
export default function items(state = initialState, action) {
  switch (action.type) {
    case UPDATE_ENTRY_LIST:
      return action.items;
    default:
      return state;
  }
}
```
是不是返回state后自动刷新界面？

**Comment by nighca** [comment]
先整理下代码格式，晚上回去细看

**Comment by nighca** [comment]
@uimake

> 147页 connect连接store与组件 Counter(props){ onClick={props.onBtnClick}}
这个onBtnClick（props属性）不是应该由父组件传入的吗，这里直接用自己的为什么不写onClick={this.onBtnClick}

`onBtnClick` 在 props 上（props 由外部传入，即 `connect` 行为的效果），而不在 `this` 上，准确地说，这里的 `Counter` 作为一个 Stateless Functional Component 甚至是不存在 `this` 这个东西的（在渲染时没有一个与之对应的实例存在）。

> 这样做是不是所有子组件的props里都有{state,actions}, 这里的state是把所有的reducer里面的初始化state都合并了？actions是把actionCreators添加dispatch后的一个手柄？

不是所有子组件，被 `connect` 的那个组件（这里即 `Deskmark`）的 `props` 里才会有 `state` 及 `actions` 字段。这里的 `state` 的内容即根 reducer 中的 `state` 内容。`actions` 的值是一个 Object，Object 的每一个字段的值对应一个绑定了 `dispatch` 的 action creator 所得到的方法。

> 另外这个state和actions能换名字吗，还是固定字段？

可以换，比如这里换成：

```javascript
const App = connect(
  state => ({ foo: state }),
  dispatch => ({ bar: bindActionCreators(actionCreators, dispatch) })
)(Deskmark);
```

的话，在组件 Deskmark 里分别改成从 `props.foo` 以及 `props.bar` 上获取状态与方法即可。

> 请问下面这个函数的执行完以后返回值是什么

如函数体中所写，函数 `fetchEntryList` 的返回值是一个箭头函数，该箭头函数接受一个参数 `dispatch`，返回一个 promise。一个普通的 action creator 应该返回一个 action Object，这里 `redux-thunk` 允许我们返回箭头函数（即 thunk）并自动执行之，`redux-promise-middleware` 允许我们返回 promise，并自动处理 promise 的结果。

> 我看updateEntryList最终执行函数是 `...`，是不是返回state后自动刷新界面？

`updateEntryList` 是一个普通的 action creator，它会返回一个 `type` 为 `UPDATE_ENTRY_LIST` 的 action Object。这个 action Object 会被 dispatch，从而被传入 reducer 里，你贴的示例代码里的 `function items()` 就是一个 reducer。它接受到这个 action 则返回新的 items 部分的 state，state 更新之后用到这部分数据的界面就会更新。dispatch action 触发 reducer 的调用是 redux 完成的，生成新的 state 后再触发界面的更新（将被 `connect` 的组件重新渲染），这是 react-redux 实现的。
