### ISSUE TITLE
第四章的例子

### ISSUE THREAD

**Issue by wdrich** [vikingmute/webpack-react-codes#18]
您好：
        最近在阅读您的教程 发现第四章的例子 打开index.html文件提示出错

Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr

       我的系统是 ubantu 16.04

**Comment by vikingmute** [comment]
可以参看这个issue，是一样的问题 https://github.com/vikingmute/webpack-react-codes/issues/10

**Comment by wdrich** [comment]
谢谢老师回复

chapter3/part4 的错误

修改package.json后
 "directories": {
    "test": "NODE_ENV=production mocha --compilers js:babel-core/register --require ignore-styles"
  },
依然报这样的错误
Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr

看您提到 文章里有说明 请告知一下页码 我去查看一下

操作系统 macos 10.12

**Comment by wdrich** [comment]
chapter4/part1 的错误
修改package.json后
  "scripts": {
    "build": "webpack",
    "dev": "webpack-dev-server --hot --host 0.0.0.0",
    "test": "NODE_ENV=production mocha --compilers js:babel-core/register --require ignore-styles"
  },
  "directories": {
    "test": "NODE_ENV=production mocha --compilers js:babel-core/register --require ignore-styles"
  },
也是报同样的错误

Error: locals[0] does not appear to be a `module` object with Hot Module replacement API enabled. You should disable react-transform-hmr in production by using `env` section in Babel configuration. See the example in README: https://github.com/gaearon/react-transform-hmr

操作系统 macos 10.12

**Comment by vikingmute** [comment]
@wdrich 你好 
我才刚发现你一开始说的是打开 index.html 报错？ 我没懂你的意思欧？这个错误应该是出现在运行npm run test 的时候的

**Comment by wdrich** [comment]
哦 我试一下
