### ISSUE TITLE
第五章的代码不完整

### ISSUE THREAD

**Issue by tgwoo** [vikingmute/webpack-react-codes#19]
part2 下只有 app.js 一个文件。
例如 P162 页有段代码引自 chapter5/part2/app/reducers/entries/list.js ，list.js 文件缺失。

**Comment by nighca** [comment]
@tgwoo 抱歉，这里写错了，应该是 [`chapter6/part2/app/reducers/entries/list.js`](https://github.com/vikingmute/webpack-react-codes/blob/master/chapter6/part2/app/reducers/entries/list.js)。
感谢反馈！
