### ISSUE TITLE
第3章第4节

### ISSUE THREAD

**Issue by Hello-Fuxq** [vikingmute/webpack-react-codes#21]
第3章第4节，
https://github.com/vikingmute/webpack-react-codes/tree/master/chapter3/part4
运行起来报一大堆的错误：
`1:1   error  Expected empty line after import statement not followed by anoth
 import  import/newline-after-import
 1:42  error  Expected linebreaks to be 'LF' but found 'CRLF'
         linebreak-style
 2:20  error  Expected linebreaks to be 'LF' but found 'CRLF'
         linebreak-style
 3:37  error  Expected linebreaks to be 'LF' but found 'CRLF'
         linebreak-style
 4:3   error  Expected linebreaks to be 'LF' but found 'CRLF'
         linebreak-style
 5:24  error  Expected linebreaks to be 'LF' but found 'CRLF'
         linebreak-style
 6:1   error  Expected indentation of 2 spaces but found 0
         indent
 6:31  error  Expected linebreaks to be 'LF' but found 'CRLF'
         linebreak-style
 7:2   error  Expected linebreaks to be 'LF' but found 'CRLF'
         linebreak-style
 8:1   error  Expected linebreaks to be 'LF' but found 'CRLF'
         linebreak-style
 9:29  error  Expected linebreaks to be 'LF' but found 'CRLF'
         linebreak-style
10:22  error  Newline required at end of file but not found
         eol-last`

我的node.js 是：“v6.9.4”，系统是：windows 7

**Comment by nighca** [comment]
@Mrs-Code 你好，这个问题看起来是你的编辑器把换行符 `\n` 自动转换成 windows 下默认的 `\r\n` 导致的，一般编辑器都可以设置不做转换
