### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by zhuyuwaiting** [vikingmute/webpack-react-codes#22]
你好！
  问题：
![image](https://cloud.githubusercontent.com/assets/9636344/22928983/25daf508-f2f4-11e6-82cb-4ffd15db5ae9.png)
我在敲的时候，告诉我这个组件无法找到，但是这个组件存在，并且在编辑器中我还可以通过 CTRL+左键 点击进去代码页，
![image](https://cloud.githubusercontent.com/assets/9636344/22929022/5c62b4a8-f2f4-11e6-9204-c7a36cfd9e99.png)
也进行了export ，但是还是告诉我找不到
![image](https://cloud.githubusercontent.com/assets/9636344/22929037/72ace06c-f2f4-11e6-9f4e-9c6778b83115.png)

如能告知 ，感激不尽

**Comment by zhuyuwaiting** [comment]
解决了 resovle的extensions 写成了extension

**Comment by nighca** [comment]
@zhuyuwaiting 好的，那 issue 先关掉啦
