### ISSUE TITLE
疑问：第4.3.4中结尾npm test

### ISSUE THREAD

**Issue by zhuyuwaiting** [vikingmute/webpack-react-codes#23]
看您的package中设置的是
 "test": "NODE_ENV=production mocha --compilers js:babel-core/register --require ignore-styles"
我在windows中跑也跑不了，然后改为了这个
"test": "set NODE_ENV=production&&mocha --compilers js:babel-core/register --require ignore-styles"；
才可以跑起来，即使在Linux中，上面mocha前面也要加 “；” 吧？

**Comment by nighca** [comment]
你好，这个问题这两个 issue（#10, #11）里也提到过，在 Windows 下面跟在 Linux / OS X 的命令不一样。

在 Linux 下是不需要 `;` 或者 `&&` 的，可以在同一行命令中进行环境变量赋值与具体操作本身。

**Comment by vikingmute** [comment]
@zhuyuwaiting 补充一点欧 其实可以使用 https://www.npmjs.com/package/cross-env 这个包来管理跨平台的问题 就不用纠结操作系统的不同了
