### ISSUE TITLE
你好，目前看到书中2个错误地方

### ISSUE THREAD

**Issue by bluefantasy728** [vikingmute/webpack-react-codes#24]
你好，有幸在读你的大作，发现有2处问题

1.第67页，整片代码的第10行，入口文件应该是app.jsx，而不是index.jsx吧，我是连着整个例子一起看的
2. 第73页，3.4.1props属性的代码块里的第三行class应该是小写

暂时发现这些问题，现在继续看第4章，祝好！

**Comment by nighca** [comment]
@bluefantasy728 感谢指出，这两点也在我们的[勘误表](https://github.com/vikingmute/webpack-react-codes/blob/master/corrigendum.md)里了。

勘误表里还有几个别的细节问题，望阅读时注意。若发现勘误表里没有的问题，欢迎继续指出，再次感谢。
