### ISSUE TITLE
第三章 70页 npm run dev报错

### ISSUE THREAD

**Issue by wangziqi0503** [vikingmute/webpack-react-codes#25]
搭建好环境后 npm run dev 报错 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle profile@1.0.0~predev: profile@1.0.0
6 silly lifecycle profile@1.0.0~predev: no script for predev, continuing
7 info lifecycle profile@1.0.0~dev: profile@1.0.0
8 verbose lifecycle profile@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle profile@1.0.0~dev: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\fan\Desktop\webpack-react-codes-master\webpack-react-codes-master\chapter3\part4\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;E:\Git\cmd;C:\Program Files\nodejs\;C:\Users\fan\AppData\Local\atom\bin;C:\Users\fan\AppData\Roaming\npm
10 verbose lifecycle profile@1.0.0~dev: CWD: C:\Users\fan\Desktop\webpack-react-codes-master\webpack-react-codes-master\chapter3\part4
11 silly lifecycle profile@1.0.0~dev: Args: [ '/d /s /c', 'webpack-dev-server --hot' ]
12 silly lifecycle profile@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle profile@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: profile@1.0.0 dev: `webpack-dev-server --hot`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid profile@1.0.0
16 verbose cwd C:\Users\fan\Desktop\webpack-react-codes-master\webpack-react-codes-master\chapter3\part4
17 error Windows_NT 10.0.10240
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
19 error node v6.2.0
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error profile@1.0.0 dev: `webpack-dev-server --hot`
22 error Exit status 1
23 error Failed at the profile@1.0.0 dev script 'webpack-dev-server --hot'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the profile package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --hot
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs profile
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls profile
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Robin-ou** [comment]
版本问题？ 我开始也遇到类似的错误，后来把npm 装的模块都换成作者的版本解决了，不知道你解决了没

**Comment by nighca** [comment]
@wangziqi0503 不好意思现在才有时间看这个问题。

麻烦确认下你本地的代码是不是跟本仓库最新的 master 一致呢，另外方便的话通过类似 nvm 这样的工具更换 node 版本为书中所用的 5.0.0，然后删除 `node_modules` 目录重新安装依赖后试试。

你提供的看起来是 `npm-debug.log` 文件的内容，不过仅根据这些信息很难定位问题。如果执行的时候命令行有输出别的跟错误相关的信息，麻烦也一并提供下。
