### ISSUE TITLE
第三章70页这边，运行npm run dev报错

### ISSUE THREAD

**Issue by yoyoemily** [vikingmute/webpack-react-codes#27]
控制台报document is not defined。  webpack: Failed to compile。
访问http://localhost:8080/  Hello React!依然是能显示出来的
然后修改内容保存也没有热更新页面内容，提示也是webpack编译失败。
不知道是不是同一问题导致的。

**Comment by nighca** [comment]
@zhutx 命令行应该有报错，麻烦提供下具体的错误内容
