### ISSUE TITLE
chapter3/part3 热加载问题

### ISSUE THREAD

**Issue by iwestlin** [vikingmute/webpack-react-codes#28]
使用的是本仓库代码，在chapter3/part3文件夹下执行 npm i 安装所需包后，再执行 npm run dev
编译成功，可以访问 http://127.0.0.1:8080/
但是修改 app.jsx 时，页面有时会刷新。比如
修改 <h1>Hello React!</h1> 为 <h1>Hello</h1>，页面刷新，丢失状态。
而如果 const app = document.createElement('div'); 去掉分号，eslint会提示错误，页面不刷新。

环境：node v7.7.2; npm v4.1.2; chrome v58; macOS 10.12.4

**Comment by nighca** [comment]
@iwestlin 你好，webpack 默认的热替换行为，会从具体变更的 module 向上依次遍历其依赖进行尝试 module 的热替换，在所有尝试都失败后，会默认采用刷新页面的方式作为 fallback。

这里我们采用的是 [`react-hmre`](https://github.com/vikingmute/webpack-react-codes/blob/master/chapter3/part3/.babelrc#L6) 这个 babel preset 进行 react component 的转换，使得包含了 react component 定义的 module 具有接受热替换的能力。不过受限于这个工具的这个版本，该能力

1. 只对非 functional stateless component 有效果
2. 在当前 module 不止包含 component 的定义，还包含了 `ReactDOM.render(<Component />, app);` 行为（如这里的 `app.jsx`）的情况下可能会工作异常

所以可以认为，包括在后续 chapter 5 / 6 中较复杂例子中，我们都没有利用对 `app.jsx` 本身做热替换的能力，主要都是利用了独立的 component 定义可以被热替换的能力。chapter3/part3 这个例子本身很简单，所有逻辑都直接写在 `app.tsx` 里了，所以可以认为是没有热替换能力的，改动就直接刷新页面。

如果要把它改成支持 component App 进行热替换的版本，把 component App 的定义写成 class 的形式，然后抽取放到旁边的独立的文件里，在 `app.tsx` 中把它 `import` 进来使用，就好了。

至于 eslint 提示错误，页面不刷新。在于这里 eslint 是一个 [`preLoader`](https://github.com/vikingmute/webpack-react-codes/blob/master/chapter3/part3/webpack.config.js#L31)，在这里边检查失败后就认为 module 编译失败，所以也就没有新的变更，也就不需要刷新页面或者更新页面，webpack 直接把这个失败的错误信息打印到 console 里了。

**Comment by iwestlin** [comment]
@nighca 多谢回复，貌似hmre这个包作者已经放弃维护了，我后来用这个实现了热替换https://github.com/gaearon/react-hot-loader
eslint的行为是我期望的那样，作为附加信息提出来的。
主要还是书上71页内容有问题，写着改变h1后页面不会刷新，搞得我以为自己配置出了问题。
在网上搜索解决办法的时候发现有人也遇到了同样的问题，最好能写进勘误表吧。。

**Comment by nighca** [comment]
@iwestlin 对的，作者后来更换了实现。

书上的内容我回去确认下哈，如果确实有问题我给加一下，你方便的话帮提个更新勘误表的 pr 就更好了。

感谢提出问题！

**Comment by iwestlin** [comment]
@nighca 不太清楚要怎样勘误比较合适，还是留给作者们吧。。感谢回复，问题可以关闭了。
