### ISSUE TITLE
看到中间不得不说的1个列子的坑

### ISSUE THREAD

**Issue by gaoxiaopang** [vikingmute/webpack-react-codes#30]
不得不吐槽这本书好多错的。。。轻微的第6页，模板字符串  vikingX  应该是name.,.还有个专业术语拼写错了，忘记是哪页，
demo：chapter4/part1/deskmark  常报错。。报错是因为...。。。主要是item，item其实在那里面是个对面，不应该用...运算符【daskmark.jsx.itemEditor.jsx】里面出现。。。。。。。然后点击文章预览时候也会报错，原因在itemshowlayer.jsx  里面。ItemShowLayer的Item里面还有个item，所以应该是const content = marked(item.item.content);而不是const content = marked(item.content);

**Comment by gaoxiaopang** [comment]
item其实在那里面是个对象

**Comment by nighca** [comment]
@gaoxiaopang 你好，感谢反馈。

你说的第一处确实是个错误，应该是

```
var a = 'My name is ' + name + '!';
```

这个我来加到[勘误表](https://github.com/vikingmute/webpack-react-codes/blob/master/corrigendum.md)里。

第二处你提到的对象使用 `...` 运算符，这个是对象展开（[Object Rest/Spread Properties](https://github.com/tc39/proposal-object-rest-spread)，现在已经 Stage 3 了）的语法，不是 ES6 的一部分，不过借助 Babel 也可以使用，在书里第 6 页以及第 192 页都有提到。

第三处你提到的 `item` 的结构，这里是没有问题的，示例代码是验证可以正常运行的。不知道是不是你本地修改了哪里的代码，导致数据结构对应不上了，麻烦检查一下。

**Comment by gaoxiaopang** [comment]
第三处。我console.log的时候看到传来的item.里面其实还是有个Item的。。你自己运行起来是没错的么，，，  第二处，我用了babel。。数组是可以用到的，但是对象一直报错。不晓得是什么原因。

**Comment by nighca** [comment]
@gaoxiaopang 你是自己写的源码还是在这个 repo 的源码基础上改的呢？如果是后者，可以 `git diff` 看下你改动了哪些地方

第二处这个问题，你的 babel 配置可能不对，可以参考下这里的 [`.babelrc`](https://github.com/vikingmute/webpack-react-codes/blob/master/chapter4/part1/.babelrc)，可以看到这里特地配置了 `transform-object-rest-spread` 这个 plugin，另外可以提供下报错的信息，未必是因为这个语法报的错

**Comment by xgqfrms-gildata** [comment]
> 数组是可以用到的，但是对象一直报错!

@gaoxiaopang 

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment

```js
// ES7 - 试验性 (尚未标准化)
// Uncaught SyntaxError: Unexpected token ...
({a, b, ...rest} = {a:1, b:2, c:3, d:4});
```

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/27716794-6bfcadb2-5d73-11e7-9e01-d2317e94ed8c.png)
