### ISSUE TITLE
Module not found: Error: Cannot resolve module 'react/lib/ReactMount'

### ISSUE THREAD

**Issue by zhoulijie** [vikingmute/webpack-react-codes#6]
按照readme去安装的，出现如下问题
```
ERROR in ./app/app.jsx
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in Documents/workspace/2016/11/webpack-react-codes/chapter6/part2/app
 @ ./app/app.jsx 1:390-421

ERROR in ./app/components/Deskmark/index.jsx
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in Documents/workspace/2016/11/webpack-react-codes/chapter6/part2/app/components/Deskmark
 @ ./app/components/Deskmark/index.jsx 1:390-421
//下面省略N行，同上的错误
```

**Comment by zhoulijie** [comment]
版本问题

**Comment by zhoulijie** [comment]
还是open吧。看到的小伙伴注意一下。

**Comment by vikingmute** [comment]
@zhoulijie 可否添加一下你什么版本出现的问题 切换到什么版本解决了问题 这样可以帮助其他人排错 谢谢～

**Comment by zhoulijie** [comment]
前几天react升级到了`15.4.0` ，把 ReactMount.js 移到 react-dom 下。
所以要么降级到`15.4.0`以前的版本，或 `node_moudles` 下找到 `react-hot-loader index.js` 将 `require('react/lib/ReactMount')` 改成 `require("react-dom").ReactMount`

建议您fix下，还有您的书写的不错

**Comment by nighca** [comment]
@zhoulijie 感谢指出，不过这个是现在使用的 react-hot-loader 版本的问题，考虑到较新的 react-hot-loader 版本均为 alpha / beta 版，升级可能带来不可预知的问题，建议在运行本代码仓库中的示例时各依赖库使用代码中指定的版本（我们已经添加了 `npm-shrinkwrap.json` 进行更精确的控制，以保证直接 `npm install` 的结果可以如预期正常运行）
如果在自己的项目使用了较新的 React 版本，这里注意下也要使用较新版本的 react-hot-loader (3.x)。
