### ISSUE TITLE
chapter3,part4/app/Hobby.jsx

### ISSUE THREAD

**Issue by madaono** [vikingmute/webpack-react-codes#8]
function Hobby() {
    return <li>{props.hobby}</li>
}
是否应该改为
function Hobby() {
    return <li>{propTypes.hobby}</li>
}
？

**Comment by nighca** [comment]
@madaono 这里应该是没有错的，见 https://github.com/vikingmute/webpack-react-codes/blob/master/chapter3/part4/app/Hobby.jsx#L7 ，源代码是

```javascript
function Hobby(props) {
  return <li>{props.hobby}</li>;
}
```

`hobby` 是 `props` 上的一个字段
